[project]
name = "demo1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai>=0.186.1",
    "crewai-tools>=0.71.0",
    "pydantic-ai>=1.0.7",
    "pypdf2>=3.0.1",
]
